version: '3.4'

services:
  hirdetorendszer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  hirdetorendszer_db:  
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: hirdetorendszer_db
    environment:  
      ACCEPT_EULA: 'Y'  
      SA_PASSWORD: "B6LPcEnxE492E5teYR8qgfqzZUdSV26a"
    volumes:
      - sqlData:/var/opt/mssql
    ports:  
      - '5010:1433'

volumes:
  sqlData:
    external: false